### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by FCYtheFreeman** [miykael/pac2018#3]
Hey,
Congrats that PAC 2018 competiton is successfully held. But sadly I knew this competiton just few days ago and I really want to take part in it. I want to train my model with those depression sMRI data too, but I can not get the download link on the official website now. So I wonder if it's possible for you to give me the download link or where I can find those data?

**Comment by miykael** [comment]
Hi there, unfortunately I don't have access anymore to the data. Perhaps you can ask the organizers and get access to the data from 2018 or even 2019. Good luck!
